language: php

php:
  - 5.4

services: mongodb

before_script:
  - pecl install mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit --coverage-text